name: calculator
description: A simple calculator app.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'  # Updated to support null safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  math_expressions: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
